// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__JSON from "@rescript/core/src/Core__JSON.res.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";

function updateJsonObjectKeyValue(jsonObject, key, value) {
  return Object.fromEntries(Core__Option.getOr(Core__Option.map(Core__JSON.Decode.object(jsonObject), (function (s) {
                        return Object.entries(s).concat([[
                                      key,
                                      value
                                    ]]);
                      })), [[
                    key,
                    value
                  ]]));
}

export {
  updateJsonObjectKeyValue ,
}
/* No side effect */
